- name: Install nginx package 
  yum: name=nginx-{{ nginx_version }} state=present 
  sudo: yes

- name: Copy nginx configuration 
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  sudo: yes
  notify: restart nginx
