- name: Install packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - bash-completion 
    - wget
    - curl
    - openssl
    - vim
    - git
    - mercurial
    - make
    - binutils
    - bison
    - gcc
